# Generated by Django 5.0.6 on 2024-10-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='food_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Unknown', max_length=255, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.TextField(blank=True, default='Unknown', max_length=200, null=True)),
                ('stock_status', models.CharField(blank=True, default='Unknown', max_length=200, null=True)),
                ('pickup_or_delivery', models.CharField(blank=True, default='Unknown', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='Unknown', max_length=255, null=True)),
            ],
        ),
    ]
