# Generated by Django 5.0.6 on 2024-10-06 01:53

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveabite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov_fname', models.CharField(blank=True, default='Unknown', max_length=255, null=True)),
                ('gov_lname', models.CharField(blank=True, default='Unknown', max_length=255, null=True)),
                ('phone_number', models.TextField(max_length=10)),
                ('birthday', models.DateField()),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('allergy', models.CharField(default='none', max_length=255)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
