# Generated by Django 5.0.6 on 2024-10-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saveabite', '0002_user_signup_delete_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_signup',
            name='country',
        ),
    ]
