# Generated by Django 5.0.6 on 2024-10-06 04:41

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveabite', '0003_remove_user_signup_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup',
            name='country',
            field=django_countries.fields.CountryField(default='Canada', max_length=2),
        ),
        migrations.AlterField(
            model_name='user_signup',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
