# Generated by Django 5.0.6 on 2024-10-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveabite', '0004_user_signup_country_alter_user_signup_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_data',
            name='allergy_rating',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='food_data',
            name='dietary_rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food_data',
            name='image',
            field=models.ImageField(upload_to='market_pics/'),
        ),
    ]
