# Generated by Django 5.0.6 on 2024-10-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveabite', '0005_food_data_allergy_rating_food_data_dietary_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_data',
            name='company_name',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
    ]
